### ISSUE TITLE
pip install instructions

### ISSUE THREAD

**Issue by mgoodhand** [linkchecker/linkchecker#108]
Thanks for reviving this project (I came here after hitting the [Requests issue](https://github.com/wummel/linkchecker/issues/593) ).

I couldn't find `pip install` instructions on https://linkcheck.github.io/linkchecker/ or in the [README](https://github.com/linkcheck/linkchecker/blob/9838ef78e93b5c0fb739bf821bebb4cee42cf9a0/README.rst). The README has a badge for https://pypi.python.org/pypi/LinkChecker, which I understand is the old version you get if you `pip install linkchecker`.

Is there a plan to get the new version on PyPI (either in place of the old one, or under a new name)?

The status quo is quite confusing (e.g. see #58), so as a first step it might be sensible to remove the PyPI link in the README and explicitly note that `pip install linkchecker` will get you the wrong version.

**Comment by mgedmin** [comment]
#4 is about getting a new PyPI release out.

**Comment by mgedmin** [comment]
I like the suggested README update.

**Comment by matkoniecz** [comment]
Is the note in the readme still necessary? I want to use this project, but I strongly prefer install in a standard way (rather than ending with cat herding and N things installed from pip, one from system packages, one via piped curl, one from github repo...)

https://pypi.org/project/LinkChecker/#history lists that 10.01 is uploaded

new PyPI release (9.4.0) #4  is closed

It seems that either new "make a new release" ticket is needed or that this "do not use pip" line could be removed from readme?

**Comment by cjmayo** [comment]
Yes, PyPI version is good enough now. README updated, with a strong hint to look at installl.txt as well.
