### ISSUE TITLE
Ironic: The description for this project links to a non-existent page

### ISSUE THREAD

**Issue by phord** [linkchecker/linkchecker#156]
On the frontpage of this repo it says 

    check links in web documents or full websites https://linkcheck.github.io/linkchecker/

When I follow that link, I get a 404 from github.io.

**Comment by anarcat** [comment]
gah.

**Comment by anarcat** [comment]
guuuh... too early in the morning, will fix soon.

**Comment by anarcat** [comment]
now fixed in https://github.com/linkcheck/linkcheck.github.io/commit/add2f85634da81ef5d8e7db348f5f45908f17da4

i don't believe there's any trace of the older URL in the newer source code as well, so we're all good...

... except i got this dang song in my head now

https://www.youtube.com/watch?v=Jne9t8sHpUc
