### ISSUE TITLE
Linkchecker reports connection errors; should re-try

### ISSUE THREAD

**Issue by SilkAndSlug** [linkchecker/linkchecker#169]
## Summary
Linkchecker reports N errors for my site. All are transitive connection errors, and could be re-tried. This happens pretty much every time I check a large-ish site.

## Steps to reproduce
This is intermittent, and (probably) affects all sites. See also [the old bug-tracker](https://github.com/wummel/linkchecker/issues/563).

 1. Check a large site, e.g. via `linkchecker --check-extern --ignore-url=^mailto: --ignore-url=^http://data-vocabulary.org --no-robots http://<redacted>`

## Actual result

    ..
    Result     Error: ConnectionError: ('Connection aborted.', BadStatusLine("''",))
    ..
    Error: ReadTimeout: HTTPSConnectionPool(host='www.<redacted>', port=443): Read timed out. (read timeout=60)
    ..
    That's it. 1084 links in 1095 URLs checked. 0 warnings found. 13 errors found.

## Expected result

    That's it. 1084 links in 1095 URLs checked. 0 warnings found. 0 errors found.

## Environment

 * Operating system: Debian 4.9.88-1+deb9u1
 * Linkchecker version: LinkChecker 9.4.0 released xx.xx.xxxx Copyright (C) 2000-2014 Bastian Kleineidam
 * Python version: Python 2.7.13
 * Install method: pip

########
    # Check a site as an unknown user
    #
    # @version
    #       9.3.3-20161118
    ########
    
    
    
    ########
    # Config
    ########
    
    [checking]
    
    # throttle
    maxrequestspersecond=1
    maxrunseconds=3600
    threads=5
    
    
    #[authentication]
    # login to site before crawling
    #entry=^https?://www\.example\.com silkandslug g3n1u55!
    #loginurl=https://www.example.com/User/Login
    #loginuserfield=user_username
    #loginpasswordfield=user_password
    #loginextrafields=
    #  name1:value1
    #  name2:value2
    
    
    
    ########
    # Plugins
    ########
    
    # check formatting & content of links
    [AnchorCheck]
    
    # check CSS
    # @todo         move to SiteChecker
    [CssSyntaxCheck]
    
    # check HTML
    # @todo         move to SiteChecker
    # @todo         broken by Bug #601 [ASCII error]
    #[HtmlSyntaxCheck]
    
    # check SSL cert is valid
    [SslCertificateCheck]
    # alert N days before expiry
    sslcertwarndays=14

### verbose run
To follow

### command-line

    linkchecker --check-extern --ignore-url=^mailto: --ignore-url=^http://data-vocabulary.org --no-robots http://<redacted>

## Other notes

1. Timed-out URLs should be marked tainted (to prevent infinite loops) and re-checked
2. Timed-out URLs should be warnings (not checked; probably okay) rather than errors (you need to fix this)

**Comment by SilkAndSlug** [comment]
The 'verbose run' is huge, and adds nothing over the non-verbose version (which doesn't say anything interesting). Here's a sample of a failing link:

    URL        `/./images/products/print/<redacted>.jpg'
    Parent URL https://<redacted>/Flowers/<redacted>, line 68, col 4
    Real URL   https://<redacted>/images/products/print/<redacted>.jpg
    Check time 5.187 seconds
    Result     Error: ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by anarcat** [comment]
i don't know about this: if a website fails, you have a problem. linkchecker works as expected. or would you just want those to be warnings instead of errors?

**Comment by regexaurus** [comment]
I see similar inconsistent (different URLs across runs) results of "ConnectionError...Connection aborted...BadStatusLine" messages. I'm not sure when the trouble started for me, but a long time ago. I'm running LinkChecker 9.4.0 on CentOS 7.5.1804, with Python 2.7.5. I primarily test sites on DreamHost shared hosting. I fiddle with the options, but a typical command looks something like:
`$ linkchecker --pause=10 -t-3 --check-extern -Fhtml/lincheckerResults.html www.example.com`

**Comment by SilkAndSlug** [comment]
@anarcat : the website *didn't* fail; that's the problem. Instead, the website was never tested (because the connection timed out). The link is untested, and I'd like LinkChecker to say as much. This is particularly a problem when the website is okay 99 times in 100, and LinkChecker claims it's got a dozen broken links the other time.

**Comment by reinholdfuereder** [comment]
Frankly, I have seen such "failure" symptoms too, but **they are in my experience NOT linkchecker problems:**
- For external links (i.e. not hosted by ourselves) they appear to be correct: of course it is hard to proof, because I cannot ask the third-party provider/hoster if they had a problem (also because they may not have sufficient APM/monitoring support to cover every single transaction, cf. at least previous versions of Dynatrace, recently re-branded to Dynatrace AppMon or so).
- And in case for our own sites I very seldom experienced something like `Error: ConnectionError: HTTPSConnectionPool(host='<DOMAIN>', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb4caea0350>` or `Error: ReadTimeout: HTTPSConnectionPool(host='<URL>', port=443): Read timed out. (read timeout=60)`
  - Then e.g. pingdom/icinga checks also showed problems during this time period: presumably the internet connection from the lab with the CI/CD server had a short temporary problem during these nightly builds

As a workaround for avoiding notification spam (false positives?) I am thus filtering out problems of external links in case the problem has not occurred more than e.g. 2 times out of the last 5 runs; this simple approach is surprisingly stable and I can live with the little delay (of needing at least 3 builds instead of just 1 build for the notification) when detecting bad links (on external sites). (And no filtering/delay for our own sites.)

Ad retry?
- If the website performance is sooo bad that a retry immediately after the problem works, then... I think the performance is just too bad (and hopefully really a third-party site and not your own)...
- In case there is a (hopefully short) maintenance window (the aim should be zero downtime bla bla...) and the whole linkchecker run takes long enough (let's say rather at least several or up to many minutes), then a 2nd retry for all found problems at the end might make sense for some of the problems (connection or read timeout, but e.g. not for a 404) **=> this could be a nice feature for linkchecker?**

HTH

**Comment by reinholdfuereder** [comment]
Jesus! My kind of boasting/swanking was punished immediately: I have just experienced such a temporary problem:
- 4 errors due to ConnectTimeout with HTTPSConnectionPool and Max retries exceeded and Caused by ConnectTimeoutError on our own website
- LinkChecker was also running with 4 threads (which might be a coincidence though)
- and the first server that gets the requests (Nginx loadbalancer) definitely has no logs for them

=> in my case the problem must be somewhere before: LinkChecker vs. Python vs. Docker vs. CI/CD Host vs. network vs. www ;-(
=> I don't have a suspicion and don't dare to guess: I guess we cannot even rule out LinkChecker and Python themselves, or can we?

**Comment by anarcat** [comment]
you could try to reproduce with only python. in the meantime, i will treat this as a non-bug because linkchecker is behaving as it should and warning you when it's failing to reach a site.

**Comment by SilkAndSlug** [comment]
@anarcat : my issue is that LinkChecker is *not* warning me when it's failing to reach a site. Instead it's erroring. I would *love* for it to merely warn me.

**Comment by SilkAndSlug** [comment]
@reinholdfuereder : I suspect you're describing different issue(s).

**Comment by SilkAndSlug** [comment]
Good point(s). 

Am I right in thinking that a broken link would return a 404? And that `BadStatusLine("''",))` -- especially if on the same domain as the initial URL -- is a symptom of a dropped connection and NOT a broken link?

If so, that's the condition I'd like to lead to a warning: the initial URL exists (status 200), but a URL on the same server can't be reached (status null). 

Status 404, etc, would still be errors.

**Comment by anarcat** [comment]
I agree the distinction between working responses from the server and
non-working responses are easy to qualify.

The problem is to distinguish between the *causes* of failures from the
server. That is a harder problem, as you need to take into account DNS,
typos in protocol and who knows what else.

For example, what if someone linked to githubb.com/linkchecker? Would
that be a warning or an error if the server fails to reply correctly?

You see where I'm going?

**Comment by yarikoptic** [comment]
I think we are experiencing similar to described here issue that linkchecker does not distinguish between unable to establish connection to a known IP/server to having established connection but failing to find a page there for a URL (404). I wonder if making retry policy more "thorough" to really try its best to establish connection would help here?  e.g. it could exponentially grow delay between retries to establish for up to a minute or two, and permit only a few retries for other causes.
