### ISSUE TITLE
get rid of MANIFEST or automate its maintenance

### ISSUE THREAD

**Issue by anarcat** [linkchecker/linkchecker#414]
we keep having issues with maintaining a good MANIFEST.in. in https://github.com/linkchecker/linkchecker/pull/410#issuecomment-633222999, @cjmayo estimates that simply getting rid of it would only add 10KB to the source distribution.

so let's just get rid of it? or what purpose does it serve? i'm not particularly familiar with it, to be honest...

**Comment by mgedmin** [comment]
Unsolicited history lesson incoming, with many wrong facts for extra fun!

MANIFEST is a file used by distutils to decide what files to include in the sdist.  If there's no manifest, distutils only includes *.py and maybe setup.cfg and README.txt?  (I don't remember the exact details, but it doesn't matter.)

Nobody uses distutils in 2020.  Everyone uses setuptools.  Setuptools have a different feature, where there's a file called MANIFEST.in that describes rules on how to generate a MANIFEST that distutils will then use.  (setuptools extends distutils and calls into it for many basic facts.)  Without a MANIFEST.in, setuptools will produce sdists that only include *.py and maybe setup.cfg and README.txt, and also README.rst since this is 2020.

There are also setuptools plugins that make it include more files, like setuptools-git or setuptools-scm will cause sdists to include all the files included in git by default.  There are reasons I don't like to rely on these plugins: you either include them in setup_requires to make sure they're present (and setup_requires is nasty, it relies on the deprecated easy_install), or you risk accidentally producing incomplete sdists when somebody runs setup.py in an environment that doesn't have the plugin.

I've been bitten enough by these problems so I wrote [check-manifest](https://pypi.org/project/check-manifest/) to make updating MANIFEST.in as painless as possible.  To keep things simple, I prefer to include all the git versioned files in my sdists.  If that's acceptable for linkchecker, I can create a PR doing that (and adding CI checks that run check-manifest).

**Comment by anarcat** [comment]
i see. i guess i don't have those problems because (a) i often use setuptools_scm and (b) i basically never build sdists :p. (I don't upload sdists to PyPI because I don't consider it necessary to make source releases there: I upload the source of my packages to Debian, since that's mandatory, and it's published on a git repo anyways, so i consider that redundant.)

So yeah, I don't really have those problems. But, of course, we might want to keep producing sdists here - i don't want to start *that* debate. :p So it seems MANIFEST.in can stay then! It would be great to check-manifest to make sure we have the right stuff in, at least, if we're going to release something...

Changed the title accordingly.

**Comment by cjmayo** [comment]
History is good. Gentoo does need a MANIFEST.in and if the version on PyPI has all tests that is ideal. A full, automated and checked MANIFEST.in sounds great, thanks.
