### ISSUE TITLE
Linkchecker doesn't run

### ISSUE THREAD

**Issue by Dale-May** [linkchecker/linkchecker#58]
Whenever I run linkchecker I get the following output:

#!C:\Python27\python.exe
#EASY-INSTALL-SCRIPT: 'LinkChecker==9.4','linkchecker'
__requires__ = 'LinkChecker==9.4'
__import__('pkg_resources').run_script('LinkChecker==9.4', 'linkchecker')

**Comment by anarcat** [comment]
How did you install linkchecker? Are you running windows by any chance? This looks like a broken installation of some sort...

**Comment by Dale-May** [comment]
Hi, anarcat. :-) I installed it on the command line using the pip installation method. My OS is Windows 10. I've reinstalled it before after having issues with PATH. (Using my work PC, so I don't have admin access.) Could that related? My other pip installed apps work fine...

**Comment by mgedmin** [comment]
That looks like the source code of the setuptools-generated wrapper script that runs the entry point.  I've no idea what set of circumstances would lead a Windows machine to print the source of a script to the console instead of running that script.

Can you provide the full commands you ran in cmd.exe (or PowerShell? whichever you used) to install and run linkchecker that resulted in this output?  "The pip installation method" is a bit vague, e.g. did you do "pip install https://github.com/linkchecker/linkchecker" or ... ?

**Comment by Dale-May** [comment]
Hi, @mgedmin. 

I installed it by entering this in Powershell: pip install linkchecker
And tried to run linkchecker in Powershell like so: linkchecker "https://... "

**Comment by mgedmin** [comment]
Thank you!

In that case pip must've downloaded Linkchecker 9.3 from the Python Packaging Index, which is the original version and not this fork.  Which is strange, since here you mentioned LinkChecker version 9.4, which is not on PyPI.

I don't understand what is happening. :(

**Comment by cjmayo** [comment]
PyPI has been updated, although at the moment it is recommended to install the current Python 3 code from GitHub.
